name: Build MakeCode Project

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-project:
    name: Build MakeCode Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Setup Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: '24'
    - run: npm install -g npm@11 --registry=https://registry.npmjs.org
    - name: Install dependencies
      run: |
        npm install -g pxt
        pxt target microbit --no-save
        pxt install
    - name: Build project cloud compiler
      run: pxt build --cloud
      env:
        CI: true