name: Build MakeCode Project

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-project:
    name: Build MakeCode Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        npm install -g pxt
        pxt target microbit --no-save
        pxt install
    - name: Build project cloud compiler
      run: pxt build --cloud
      env:
        CI: true